# Deploy the Docker image on a defined server
name: Deploy Minebot

on:
  push:
    branches:
      - "branches/deploy_docker_build"

jobs:
  deploy-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
    
    steps:
      - name: Create .env file
        shell: bash
        run: |
          mkdir config
          echo "ENVIRONMENT=PROD" >> ./config/.env
          echo "DISCORDBOT_TOKEN=${{ secrets.CD_DISCORD_BOT_PROD_TOKEN }}" >> ./config/.env
          echo "DISCORDBOT_CLIENT_ID=${{ secrets.CD_DISCORD_BOT_PROD_CLIENT_ID }}" >> ./config/.env
          echo "SCA_API_TOKEN=${{ secrets.CD_SCA_API_PROD_TOKEN }}" >> ./config/.env
      
      - name: Setup ssh
        shell: bash
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.CD_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.CD_SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy docker-compose.yml and config
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.CD_SSH_SERVER_HOST }}
          port: 5634
          username: ${{ secrets.CD_SSH_USERNAME }}
          key: ${{ secrets.CD_SSH_PRIVATE_KEY }}
          fingerprint: ${{ secrets.CD_SSH_KNOWN_HOSTS }}
          source: "config,docker/docker-compose.yml"
          target: ${{ secrets.CD_SSH_WORK_DIR }}
      
      - name: Restart Docker image
        shell: bash
        run: |
          ssh -p ${{ secrets.CD_SSH_SERVER_PORT }} ${{ secrets.CD_SSH_USERNAME }}@${{ secrets.CD_SERVER_HOST }} '''
            cd ${{ secrets.CD_SSH_WORK_DIR }}
            docker compose up --env-file ./config/.env -d
          '''
