# Deploy the Docker image on a defined server
name: Deploy Minebot

on:
  push:
    branches:
      - "branches/deploy_docker_build"

jobs:
  deploy-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create .env file
        shell: bash
        run: |
          mkdir config
          echo "ENVIRONMENT=PROD" >> ./config/.env
          echo "DISCORDBOT_TOKEN=${{ secrets.CD_DISCORD_BOT_PROD_TOKEN }}" >> ./config/.env
          echo "DISCORDBOT_CLIENT_ID=${{ secrets.CD_DISCORD_BOT_PROD_CLIENT_ID }}" >> ./config/.env
          echo "SCA_API_TOKEN=${{ secrets.CD_SCA_API_PROD_TOKEN }}" >> ./config/.env

      - name: Deploy docker-compose.yml and config
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.CD_SERVER_HOST }}
          port: 5634
          username: ${{ secrets.CD_SSH_USERNAME }}
          key: ${{ secrets.CD_SSH_PRIVATE_KEY }}
          source: "config,docker/docker-compose.yml"
          target: ${{ secrets.CD_SSH_WORK_DIR }}
  
  restart-image:
    runs-on: ubuntu-latest
    needs: deploy-image

    permissions:
      contents: read
      packages: read

    steps:
      - name: Restart Docker image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.CD_SERVER_HOST }}
          port: 5634
          username: ${{ secrets.CD_SSH_USERNAME }}
          key: ${{ secrets.CD_SSH_PRIVATE_KEY }}
          script: |
              cd ${{ secrets.CD_SSH_WORK_DIR }}
              docker compose -f ./docker/docker-compose.yml --env-file ./config/.env up -d
