# Publish a Docker image on the project on the release of a new version
name: Publish Docker

on:
  push
  # release:
  #   types: [ "published" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GH Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Doker
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
      - name: Build and Push 🐋
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: ${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}